ALTER TABLE "CameraConfig"
ADD COLUMN "previewPanX" DECIMAL(6,4) NOT NULL DEFAULT 0,
ADD COLUMN "previewPanY" DECIMAL(6,4) NOT NULL DEFAULT 0,
ADD COLUMN "previewRotation" DECIMAL(6,2) NOT NULL DEFAULT 0;
